In [82]:
from pymatgen.ext.matproj import MPRester
from pymatgen.io.cif import CifWriter
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
from pymatgen.core.operations import SymmOp
from IPython.display import Markdown,display
import numpy as np
def printbold(string): 
    display(Markdown(string))


with MPRester("gsItyjn65HPAFPdGywpu") as m:
    structure = m.get_structure_by_material_id("mp-47")
    w = CifWriter(structure, 0.1)
    w.write_file('C_mp-47_symmetrized.cif')

printbold("**Téléchargement du fichier CIF...**")

**Téléchargement du fichier CIF...**

In [83]:
printbold("**Maille et structure du matériau mp-47**")
print("Maille :")

**Maille et structure du matériau mp-47**

Maille :


![](mp47.jpg)

In [84]:
print("Structure :")

Structure :


![](mp47plane.jpg)

In [86]:
printbold("**Application de la 1ère symétrie : (x-y, x, z+1/2)**")
print("Cette opération de symétrie est une roto-translation d'ordre 6 et de coefficient de translation 1/2,")
print("l'élément de symétrie est donc un axe hélicoïdal 6_3.")
print("Une roto-translation est une opération non symorphique et se constitue d'une partie ponctuelle et d'une partie")
print("translatoire.")
print("Partie ponctuelle : matrice de la rotation ")
m1=SymmOp.from_xyz_string('x-y, x, z+1/2')
print(m1.rotation_matrix)
print("Partie translatoire : vecteur de translation")
print(m1.translation_vector)
print("On applique cette roto-translation sur le carbone en position (0.33 , 0.67 , 0.06) :")
carbone1=np.array([[0.33], [0.67], [0.06]])
sym1 = np.dot(m1.rotation_matrix,carbone1) + np.array([[0], [0], [0.5]])


**Application de la 1ère symétrie : (x-y, x, z+1/2)**

Cette opération de symétrie est une roto-translation d'ordre 6 et de coefficient de translation 1/2,
l'élément de symétrie est donc un axe hélicoïdal 6_3.
Une roto-translation est une opération non symorphique et se constitue d'une partie ponctuelle et d'une partie
translatoire.
Partie ponctuelle : matrice de la rotation 
[[ 1. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]
Partie translatoire : vecteur de translation
[0.  0.  0.5]
On applique cette roto-translation sur le carbone en position (0.33 , 0.67 , 0.06) :


![](mp47calcul1.png)

In [87]:
print("En voici une représentation visuelle :")

En voici une représentation visuelle :


![](mp47_sym3.jpg)

In [88]:
printbold("**Application de la 2ème symétrie : (x, y, -z+1/2)**")
print("Cette opération de symétrie est une symétrie miroir, dont l'élément de symétrie est un plan parallèle au plan")
print("formé par a et b et en z = 1/4.")
print("L'opération de symétrie comporte à nouveau une partie ponctuelle et une partie translatoire.")
print("Partie ponctuelle : matrice de rotation")
m2 = SymmOp.from_xyz_string('x, y, -z+1/2')
print(m2.rotation_matrix)
print("Partie translatoire : vecteur de translation")
print(m2.translation_vector)
print("On applique cette opération de symétrie au carbone en position (0.67, 0.33, 0.94) :")
sym2= np.dot(m2.rotation_matrix, np.array([[0.67],[0.33],[0.94]])) + np.array([[0],[0],[0.5]])

**Application de la 2ème symétrie : (x, y, -z+1/2)**

Cette opération de symétrie est une symétrie miroir, dont l'élément de symétrie est un plan parallèle au plan
formé par a et b et en z = 1/4.
L'opération de symétrie comporte à nouveau une partie ponctuelle et une partie translatoire.
Partie ponctuelle : matrice de rotation
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0. -1.]]
Partie translatoire : vecteur de translation
[0.  0.  0.5]
On applique cette opération de symétrie au carbone en position (0.67, 0.33, 0.94) :


![](mp47calcul2.png)

In [89]:
print("En voici une représentation visuelle :")

En voici une représentation visuelle :


![](mp47_sym8.jpg)

In [90]:
printbold("**Application de la 3ème symétrie : (-x+y, -x, z)**")
print("Cette opération de symétrie est une rotation d'ordre 3, ce qui implique une rotation de 2pi/3 à chaque")
print("application de l'opération, dont l'axe est orienté selon z.")
print("Les simples rotations sont constituées uniquement d'une partie ponctuelle.")
m3 = SymmOp.from_xyz_string('-x+y, -x, z')
print("Matrice de rotation :")
print(m3.rotation_matrix)
print("On applique cette opération de symétrie au carbone en position (0.67, 0.33, 0.56) :")
sym3 = np.dot(m3.rotation_matrix, np.array([[0.67],[0.33],[0.56]]))

**Application de la 3ème symétrie : (-x+y, -x, z)**

Cette opération de symétrie est une rotation d'ordre 3, ce qui implique une rotation de 2pi/3 à chaque
application de l'opération, dont l'axe est orienté selon z.
Les simples rotations sont constituées uniquement d'une partie ponctuelle.
Matrice de rotation :
[[-1.  1.  0.]
 [-1.  0.  0.]
 [ 0.  0.  1.]]
On applique cette opération de symétrie au carbone en position (0.67, 0.33, 0.56) :


![](mp47calcul3.png)

In [91]:
print("En voici deux représentations visuelles. La première permet de visualiser l'opération dans le cristal en ")
print("trois dimensions, tandis que la seconde permet de clarifier la chose en se plaçant dans un plan de normale")
print("orientée selon l'axe de rotation :")

En voici deux représentations visuelles. La première permet de visualiser l'opération dans le cristal en 
trois dimensions, tandis que la seconde permet de clarifier la chose en se plaçant dans un plan de normale
orientée selon l'axe de rotation :


![](mp47_sym9.1.jpg)

![](mp47_sym9.2.jpg)